### ISSUE TITLE
Support for chrome

### ISSUE THREAD

**Issue by yasintz** [pass-wall/passwall-extension#2]

**Comment by yakuter** [comment]
@bufgix said this project can be easily converted for Chrome. I think we should first work on this repo quickly. Then we can convert this to Chrome. Or do you have any other roadmap? Can we use same repo for both chrome and firefox?

**Comment by yasintz** [comment]
We can use the same repo.
While it is developing, it may be helpful to think it will work on chrome as well.

**Comment by yakuter** [comment]
Then do you think we can change repo name to passwall-extension (remove firefox) ?

**Comment by yasintz** [comment]
Yep @yakuter

**Comment by bufgix** [comment]
I'm working on it

**Comment by bufgix** [comment]
#5

**Comment by yakuter** [comment]
I already changed the name.
