### ISSUE TITLE
use mozilla's webextension polyfill instead of explicit usage

### ISSUE THREAD

**Issue by mtoygar** [pass-wall/passwall-extension#7]
the below library(👇 ) polyfills webextension APIs. The polyfill may ease the handling of cross-browser extension development. What do you think about such an approach?

> This library allows extensions that use the Promise-based WebExtension/BrowserExt API being standardized by the W3 Browser Extensions group to run on Google Chrome with minimal or no changes.

https://github.com/mozilla/webextension-polyfill
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

**Comment by bufgix** [comment]
I switched some chrome APIs to Promise-based. Like this;
https://github.com/pass-wall/passwall-extension/blob/449c6a2707985ff35a061ecf623d43261a0dd348/src/utils.js#L49

but we can use polyfill instead of my implementation.

**Comment by yakuter** [comment]
I don't know if it is hard to switch to polyfill but we need to take the right steps when you are at the beginning of the road. Polyfill seems like the right way, isn't it? I don't know, just asking.

**Comment by bufgix** [comment]
Yes. Polyfill is the right way. We can use it. I'll open PR

**Comment by bufgix** [comment]
#8

**Comment by yakuter** [comment]
No more if (BROWSER_TYPE === "firefox") directives :) Thank you. Great job.

**Comment by mtoygar** [comment]
I have a small comment/feedback regarding issue process. IMHO, after deciding implementing the proposed feature you may ask the issue owner, whether or not s/he would be interested in implementing. In that case the implementation may take more time but project can gain more contributors. With a proper PR review, you can achieve code quality.

**Comment by yakuter** [comment]
@mtoygar you are completely right about it. Everyone is very excited about the project. So these kind of innocent mistakes can be made. I'm still learner on the project management side. I will be careful about your feedback.

@bufgix from now on, let's first talk about issue, then assign the contributor and make the job done. The assignee should be the issue owner first if he/she wants. 

Is this alright for everyone?
